#!/usr/bin/env php
<?php

exit(call_user_func(function () {
    define('ARTEFAKT_START', microtime(true));

    // Require the autoloader
    $directory = __FILE__;
    while ($directory && !is_dir($directory.DIRECTORY_SEPARATOR.'vendor')) {
        $directory = dirname($directory);
    }
    require $directory.DIRECTORY_SEPARATOR.'vendor'.DIRECTORY_SEPARATOR.'autoload.php';

    // Bootstrap Artefakt and return a CLI interface
    \Artefakt\Core\Ports\Artefakt::cli()->run();
}));

